export const calculatorButtons = [
    { value: "AC", isAction: true },
    { value: "DEL", isAction: true },
    { value: "%", isOperator: true },
    { value: "÷", isOperator: true },
    { value: "7" },
    { value: "8" },
    { value: "9" },
    { value: "×", isOperator: true },
    { value: "4" },
    { value: "5" },
    { value: "6" },
    { value: "-", isOperator: true },
    { value: "1" },
    { value: "2" },
    { value: "3" },
    { value: "+", isOperator: true },
    { value: "0", isDouble: true },
    { value: "." },
    { value: "=", isOperator: true },
];